services:
  db:
    container_name: db
    image: postgres:${POSTGRES_IMAGE_TAG:-latest}
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - 5432:5432
    networks:
      - nextjs-dashboard-network

  adminer:
    container_name: adminer
    image: adminer:${ADMINER_IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - nextjs-dashboard-network

volumes:
  db-data:

networks:
  nextjs-dashboard-network:
    driver: bridge